yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/includes/add_com.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}

yatube/templates/includes/footer.html
<div class="footer-copyright text-center py-3"> 
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p> 
</div>    

yatube/templates/includes/form_create.html
{% load user_filters %}
{% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}

yatube/templates/includes/form_errors.html
<div class="card-body">
    {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}            
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
        {% endfor %}
    {% endif %}

yatube/templates/includes/header.html
{% load static %} 
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src={% static "img/logo.png" %} width="30" height="30" class="d-inline-block align-top" alt="">
          <span style="color:red">Ya</span>tube
        </a>
        {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
            href="{% url 'about:author' %}">Об авторе</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
            href="<{% url 'about:tech' %}>">Технологии</a>
          </li>
          {% if user.is_auntificated %}
          <li class="nav-item"> 
            <a class="nav-link " href="<{% url 'posts:post_create'%}>">Новая запись</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'users:author_change_form' %}active{% endif %}" 
            href="{% url 'users:author_change_form' %}">Изменить пароль</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}" 
            href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
          {% else %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}" 
            href="{% url 'users:login' %}">Войти</a>
          </li> 
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}"
             href="{% url 'users:signup' %}">Регистрация</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% endwith %}     
 

yatube/templates/includes/post_card.html
{% load thumbnail %}
<article> 
    <ul> 
      <li> 
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
      </li> 
      <li> 
        Дата публикации: {{ post.pub_date|date:"d E Y" }} 
      </li> 
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}     
      <p> 
        {{ post.text }} 
      </p>         
    </article>

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}