yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Имя группы')
    slug = models.SlugField(unique=True)
    description = models.TextField(verbose_name='Содержание')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Группа',
        blank=True,
        null=True,
        on_delete=models.SET_NULL
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(verbose_name='Текст комментария')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации коммента'
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following"
    )

yatube/posts/forms.py
from xml.etree.ElementTree import Comment

from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.cache import cache_page

from posts.forms import CommentForm, PostForm
from posts.models import Follow, Group, Post, User

PAGES = 10


def pagination(request, posts):
    paginator = Paginator(posts, PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


@cache_page(20, key_prefix='index_page')
def index(request):
    posts = Post.objects.all()
    page_obj = pagination(request, posts)
    context = {
        'page_obj': page_obj}
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group)
    page_obj = pagination(request, posts)
    context1 = {'group': group,
                'page_obj': page_obj}
    return render(request, 'posts/group_list.html', context1)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=author)
    page_obj = pagination(request, posts)
    following = (
        request.user.is_authenticated and Follow.objects.filter(
            user=request.user, author=author).exists() and (
            request.user != author)
    )
    context = {'author': author,
               'page_obj': page_obj,
               'following': following}
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm()
    comments = post.comments.all()
    context = {'post': post,
               'comments': comments,
               'form': form}
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect('posts:profile', request.user)
        return render(request, 'posts/create_post.html', {'form': form})
    form = PostForm()
    context = {'form': form}
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    author = post.author
    if author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'post': post,
        'is_edit': True}
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = pagination(request, posts)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=user, author=author)
    if user != author and not is_follower.exists():
        Follow.objects.create(user=user, author=author)
    return redirect(reverse('posts:profile', args=[username]))


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    {% block title %}
      {% if post %}
        Редактирование поста
      {% else %}
        Новый пост
      {% endif %}
    {% endblock %}
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">             
              </div>
              <div class="card-body">
                {% include 'includes/form_errors.html' %}
                {% if is_edit %}
                <form action="{% url 'posts:post_edit' post.pk %}" enctype="multipart/form-data" method="post"> 
                {% else %}
                <form action="{% url 'posts:post_create' %}" enctype="multipart/form-data" method="post">
                {% endif %}        
                  {% csrf_token %}          
                  {% include 'includes/form_create.html' %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if post %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                    {% if post.group %}
                    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                    {% endif %}
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endblock%}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
<title> Лента постов  </title>
{% load thumbnail %}
{% load cache %}
{% block content %}
  <div class="container py-5">     
    <h1> Последние обновление ленты </h1>
    {% cache 20 index_page %}
    {% include 'includes/switcher.html' %}
        {% for post in page_obj %}
        <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}     
          <p>
            {{ post.text }}
          </p>
          <p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
          </p>   
          {% if post.group %}   
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}         
        </article>
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% endcache %}
        {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load static %}
{% block head_title %}
 Записи сообщества {{ group.title }}
{% endblock %}
{% block content %} 
  <div class="container py-5">     
    <h1> {{ group.title }} </h1> 
    <p> 
      {{ group.description }} 
      </p> 
        {% for post in page_obj %} 
        {% include 'includes/post_card.html' %}
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
        {% if post.group %}   
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}  
        {% if not forloop.last %}<hr>{% endif %} 
        {% endfor %} 
  </div> 
        {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
<title> Это главная страница проекта Yatube </title>
{% load thumbnail %}
{% load cache %}
{% block content %}
  <div class="container py-5">     
    <h1> Последние обновления на сайте </h1>
    {% cache 20 index_page %}
    {% include 'includes/switcher.html' %}
        {% for post in page_obj %}
        <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}     
          <p>
            {{ post.text }}
          </p>
          <p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
          </p>   
          {% if post.group %}   
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}         
        </article>
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% endcache %}
        {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} Пост {{ post.text|truncatechars:30 }} {% endblock %}
{% load thumbnail %}
{% block content %}
<div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        {% if post.group %}   
        <li class="list-group-item">
          <p> Группа: {{ post.group }} </p>
          <a href="<{% url 'posts:group_list' post.group.slug %}>">все записи группы</a>
        {% endif %}
        </li>
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span > {{ post.author.posts.count }} </span>
        </li>
        <li class="list-group-item">
          <a href="<{% url 'posts:profile' post.author.username %}>">все посты пользователя</a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      {% if  post.author == request.user %}
        <a href="<{% url 'posts/create_post.html'%}>" class="btn btn-primary">Редактировать</a> 
        {% endif %}
        {% if request.user.is_authenticated %}
        {% include 'includes/add_com.html' %}
        {% else %}
        Оставить комментарий может только избранный
        {% endif %}
    </article>
  </div> 
{% endblock%}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя {{ author.get_full_name }} {% endblock %}
{% load thumbnail %}
{% block content %}
<div class="container py-5">        
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>
    {% include 'posts/includes/following.html' %}
    {% for post in page_obj %}   
        <article>
        <ul>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}     
          <p>
          {{ post.text }}
          </p>
          <p>
          <a href="<{% url 'posts:post_detail' post.id %}>">подробная информация </a>
          </p>
          {% if post.group %}      
          <a href="<{% url 'posts:group_list' post.group.slug %}>">все записи группы</a>
          {% endif %}              
        </article>
        {% if not forloop.last %}<hr>{% endif %}        
        {% endfor %}       
        {% include 'posts/includes/paginator.html' %}  
  </div>
{% endblock %}